# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-check
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
    - ls -l build/libs/
  artifacts:
    paths:
      - build/libs/
      - build/classes/

test:
  stage: test
  script:
    - ./gradlew test

sonarqube-check:
  stage: sonarqube-check
  script:
    - ./gradlew sonar test jacocoTestReport

deploy:
  stage: deploy
  script:
    - docker-compose up --build -d
