spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://petpal-db:3306/petpal-db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
spring.flyway.enabled=true
cors.allowed-origin=http://localhost:5173

