spring.application.name=PetPal
spring.profiles.active=default
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://petpal-db:3306/petpal-db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
spring.flyway.enabled=true
cors.allowed-origin=http://localhost:5173
jwt.secret=bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXk=

weather.api.url=https://api.openweathermap.org/data/2.5/weather
weather.api.key=21185c0f49519b589ef90cf18f0f450c

openrouter.api.url=https://openrouter.ai/api/v1/completions
openrouter.api.key=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
openrouter.model=meta-llama/llama-3.2-1b-instruct:free

server.servlet.context-path=/backend