apiVersion: v1
kind: Secret
metadata:
  name: petpal-secret
  namespace: petpal
type: Opaque
stringData:
  DB_PASSWORD: changeme
  DB_PASSWORD_TEST: changeme-test
  JWT_SECRET: bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXk=
  WEATHER_API_KEY: 21185c0f49519b589ef90cf18f0f450c
  OPENROUTER_API_KEY: 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
